services:
  postgres:
    image: postgres:16
    container_name: enterprise-iam-db

    environment:
      POSTGRES_DB: enterprise_iam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: